# Generated by Django 5.2.9 on 2025-12-12 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('is_deposit_protected', models.BooleanField(default=False)),
                ('is_non_face_to_face', models.BooleanField(default=False)),
                ('prefer_condition_text', models.TextField(blank=True)),
                ('base_rate', models.FloatField(blank=True, null=True)),
                ('max_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_terms_months', models.IntegerField()),
                ('base_rate', models.FloatField(null=True)),
                ('max_rate', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='products.product')),
            ],
        ),
    ]
